import type { ProductData } from "@/components/commerce/ProductCard";

// Mock product data for prototype
// categoryId references the deepest category in lib/categories.ts
export const mockProducts: ProductData[] = [
  {
    id: "1",
    name: "Panadol Extra 500mg Tablets - 24 Pack",
    brand: "Panadol",
    imageUrl: "/images/products/placeholder.svg",
    price: 45.0,
    pickupPrice: 42.0,
    originalPrice: 60.0,
    discountPercent: 25,
    badges: [{ label: "-25%", variant: "discount" }],
    hasVariants: false,
    inStock: true,
    quantityOffer: "Buy 2, Get 1 Free",
    rating: 4,
    categoryId: "med-pain-tab",
  },
  {
    id: "2",
    name: "Centrum Multivitamins Adults 60 Tablets",
    brand: "Centrum",
    imageUrl: "/images/products/placeholder.svg",
    price: 320.0,
    hasVariants: true,
    inStock: true,
    badges: [{ label: "Best", variant: "best-seller" }],
    rating: 5,
    categoryId: "vit-multi-adult",
  },
  {
    id: "3",
    name: "CeraVe Moisturizing Cream 340g",
    brand: "CeraVe",
    imageUrl: "/images/products/placeholder.svg",
    price: 580.0,
    pickupPrice: 550.0,
    originalPrice: 650.0,
    discountPercent: 10,
    hasVariants: false,
    inStock: true,
    badges: [{ label: "-10%", variant: "discount" }],
    categoryId: "skin-moist-face",
  },
  {
    id: "4",
    name: "Augmentin 625mg Antibiotics",
    brand: "GSK",
    imageUrl: "/images/products/placeholder.svg",
    price: 85.0,
    hasVariants: false,
    inStock: true,
    requiresPrescription: true,
    badges: [{ label: "RX", variant: "prescription" }],
    categoryId: "med-anti-cap",
  },
  {
    id: "5",
    name: "Voltaren Emulgel 1% Pain Relief 50g",
    brand: "Voltaren",
    imageUrl: "/images/products/placeholder.svg",
    price: 120.0,
    hasVariants: false,
    inStock: true,
    badges: [{ label: "New", variant: "new" }],
    rating: 4,
    categoryId: "med-pain-top",
  },
  {
    id: "6",
    name: "Pampers Premium Care Diapers Size 4 - 66 Count",
    brand: "Pampers",
    imageUrl: "/images/products/placeholder.svg",
    price: 450.0,
    pickupPrice: 430.0,
    originalPrice: 520.0,
    discountPercent: 13,
    hasVariants: true,
    inStock: true,
    badges: [{ label: "-13%", variant: "discount" }],
    rating: 5,
    categoryId: "baby-diaper",
  },
  {
    id: "7",
    name: "Bioderma Sensibio H2O Micellar Water 500ml",
    brand: "Bioderma",
    imageUrl: "/images/products/placeholder.svg",
    price: 380.0,
    hasVariants: false,
    inStock: false,
    badges: [{ label: "Few Left", variant: "low-stock" }],
    categoryId: "skin-clean-mic",
  },
  {
    id: "8",
    name: "Nature's Bounty Vitamin D3 1000 IU - 120 Softgels",
    brand: "Nature's Bounty",
    imageUrl: "/images/products/placeholder.svg",
    price: 210.0,
    hasVariants: false,
    inStock: true,
    quantityOffer: "Buy 3 for 500 EGP",
    rating: 4,
    categoryId: "vit-bone-d",
  },
  {
    id: "9",
    name: "Bepanthen Nappy Care Ointment 100g",
    brand: "Bepanthen",
    imageUrl: "/images/products/placeholder.svg",
    price: 195.0,
    hasVariants: false,
    inStock: true,
    rating: 5,
    categoryId: "baby-skin",
  },
  {
    id: "10",
    name: "Avene Thermal Spring Water Spray 300ml",
    brand: "Avene",
    imageUrl: "/images/products/placeholder.svg",
    price: 290.0,
    pickupPrice: 275.0,
    originalPrice: 350.0,
    discountPercent: 17,
    hasVariants: false,
    inStock: true,
    badges: [{ label: "-17%", variant: "discount" }],
    rating: 3,
    categoryId: "skin-sun-sc",
  },
];

export const mockTrendingSearches = [
  "Skincare",
  "Vitamins",
  "Baby Formula",
  "Hair Loss",
  "Sunscreen",
  "Pain Relief",
];

export const mockRecentSearches = [
  "Panadol",
  "Vitamin C",
  "CeraVe moisturizer",
];
